<a href="https://colab.research.google.com/github/AFNANAMIN/AI_Freelancing/blob/master/federated_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#lets create a vetor dataset

import torch
num_entries=5000 #total entries in the dataset 
data=torch.rand(num_entries)>0.5
data[0:6]

tensor([False,  True,  True,  True,  True,  True])

In [21]:
#so we want to remove 3rd entry from this
remove_index=2
data[0:2]#indices before the entry
data[3:]#indices after the entry


tensor([ True,  True,  True,  ..., False, False,  True])

In [22]:
torch.cat((data[0:2],data[3:]))[0:6]#remove 3rd entry

tensor([False,  True,  True,  True,  True,  True])

In [0]:
#now make the function of get parallel db
def get_parallel_db(remove_index,db):
  return torch.cat((db[0:remove_index],db[remove_index+1:]))[0:6]

In [24]:
get_parallel_db(2,data)#we still get the same functionality

tensor([False,  True,  True,  True,  True,  True])

In [0]:
#let create a list of parallel databases
def get_parallel_dbs(db):
    parallel_db=list()
    for i in range(len(db)):
          pdb=get_parallel_db(2,db)
          parallel_db.append(pdb)
    return parallel_db

In [0]:
pdbs=get_parallel_dbs(data)

In [27]:
pdbs

[tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  True]),
 tensor([False,  True,  True,  True,  True,  T

In [0]:
def create_db_and_parallel(num_entries):
  db=torch.rand(num_entries)>0.5
  pdbs=get_parallel_dbs(db)

  return db,pdbs



In [29]:
db,pdbs=create_db_and_parallel(20)#database with 20 entries each
db

tensor([ True,  True,  True, False, False, False, False,  True, False, False,
         True,  True,  True,  True, False,  True,  True,  True,  True, False])

In [30]:
pdbs

[tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, False]),
 tensor([ True,  True, False, False, False, Fa

Now we intimate that quering the database doesn't leak any private information 

In [0]:
def query(db):
  return db.sum()

In [0]:
db_query_result=query(db)#its means 7 true values in our database

In [33]:
query(pdbs[3])

tensor(2)

In [34]:
#let calculate how much the query changes when we remove someone from the database
max_distance=0
for pdb in pdbs:
  pdb_query_result=query(pdb)
  db_distance=torch.abs(pdb_query_result-db_query_result)
  if (db_distance>max_distance):
    max_distance=db_distance

 
max_distance#this is basically the sensitivity of our database

tensor(10)

EVALUATING THE PRIVACY OF A FUNCTION

In [35]:
#attcaking dp
sum(db)-sum(pdb)

tensor(10)